global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ZENTRAVIX-api'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/api/metrics'

  - job_name: 'ZENTRAVIX-ai-engine'
    static_configs:
      - targets: ['ai-engine:8001']
    metrics_path: '/metrics'
